### ISSUE TITLE
Media properties are not showing in Data Type configuration

### ISSUE THREAD

**Issue by akeilox** [OPTEN/OP10-Multiple-Media-Picker#9] opened 2017-04-07 08:17 UTC
I have just updated to latest 1.2
running Umbraco version 7.5.9 assembly: 1.0.6247.17495

When I go to Developers->Data Type-> OP10 Multiple Media Picker instance
Media properties are not showing in the selection/ configuration

Would like to add I have already custom properties on the Image Media Type like
defaultNodeName
physicalName
imageDescription

**Comment by Nora0707** [comment] 2017-06-23 15:09
Hi akeilox, did you find a solution for your problem? I'm experiencing the same with a installation that already has been updated and has lot's of media items.

**Comment by akeilox** [comment] 2017-06-23 18:31
Hi @Nora0707 

Unfortunately I didn't find a solution, having since upgraded to Umbraco 7.6 and the package not marked as 7.6 tested I didn't pursue further, awaiting update from @AaronMorf - package maintainer.

**Comment by Nora0707** [comment] 2017-06-24 06:37
I installed and used it on a 7.6 installation and it seems to work well - we are using the plugin for most of our projects, as it's really useful. Just got this problem on one installation. As soon as I'll find out something I'll let you know.

**Comment by AaronMorf** [comment] 2017-06-28 15:40
Hi @akeilox
Sorry for the late response.
Did you add the properties "defaultNodeName" and "physicalName" by your own? 
If so, you do not need to do that and that may have caused the error. It automatically generates for all media types those properties which save something on the server such as the Image media type does.

Otherwise if you just updated it could be that an old version of the dll was still somewhere around in the cache.

**Comment by Nora0707** [comment] 2017-06-30 15:15
Hmm ... I've experienced this problem on a 7.2.8 installation with old media data and a variety of custom properties on the image data type. Now I've got a 7.4.3 fresh install - I installed OP10 Media Picker and configured it, everything perfect. Then I added a custom property on the image data type and the option to select any property in the OP10 data type disappears, deleting the new custom property again doesn't change anything. Any ideas? 
![grafik](https://user-images.githubusercontent.com/22796412/27742069-9a307e5e-5db7-11e7-9309-2ae530fb9cbe.png)

**Comment by Nora0707** [comment] 2017-06-30 15:47
As soon as I select a quick-view property and save, these checkboxes also disappear. The only error I see in the log that could be related to the problem is:  
WARN Umbraco.Web.Models.Mapping.PreValueDisplayResolver – Could not find persisted pre-value for field crops
WARN Umbraco.Web.Models.Mapping.PreValueDisplayResolver – Could not find persisted pre-value for field startNodeId

**Comment by AaronMorf** [comment] 2017-07-03 06:23
There was a problem with the default value for the "Allow items of type". It should have been by default "Image" but there was a bug which is now fixed in version 1.2.2.
So you should update the package or if you just type in "Image" for the "Allow items of type" property it should also work again.

**Closed as completed** 2017-07-03 06:24 UTC

**Comment by Nora0707** [comment] 2017-07-03 14:37
Hi Aaron, thanks a lot for the update and your immediate response.

**Comment by akeilox** [comment] 2017-07-05 04:39
Hi @AaronMorf 
Thanks for the update. 
a) I have since uninstalled the previous Op10 multiple media picker, reinstalled from package manager (1.2.2) and 
b) had to go Developer->Data Types-> select previously created data type and re-edit its pre-values (like remove Image only etc.

If I didnt carry point b, the previously created data type was not showing up the properties even after upgrading to 1.2.2 simply.
Carrying these two steps make it all work nicely in 7.6.1 install. Sharing here for others following the same path as me.

Many thanks for looking into it.

**Comment by AaronMorf** [comment] 2017-07-05 12:19
Hi @akeilox
Thanks for the hint.
I will have a look at it but for the moment it will work by minding these two steps you mentioned.
